// Structured error codes for Agent consumption
export enum ErrorCode {
  ELEMENT_NOT_FOUND = 'ELEMENT_NOT_FOUND',
  NAVIGATION_TIMEOUT = 'NAVIGATION_TIMEOUT',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  PAGE_CRASHED = 'PAGE_CRASHED',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  EXECUTION_ERROR = 'EXECUTION_ERROR',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  RUN_NOT_FOUND = 'RUN_NOT_FOUND',
  RUN_TIMEOUT = 'RUN_TIMEOUT',
  // v0.2 additions
  RUN_CANCELED = 'RUN_CANCELED',
  STEP_EXECUTION_FAILED = 'STEP_EXECUTION_FAILED',
  TRUST_LEVEL_NOT_ALLOWED = 'TRUST_LEVEL_NOT_ALLOWED',
  TEMPLATE_VERSION_UNSUPPORTED = 'TEMPLATE_VERSION_UNSUPPORTED',
  ARTIFACT_NOT_FOUND = 'ARTIFACT_NOT_FOUND',
  ARTIFACT_EXPIRED = 'ARTIFACT_EXPIRED',
  TPL_LOGIN_FIELD_NOT_FOUND = 'TPL_LOGIN_FIELD_NOT_FOUND',
}
